services:
  - type: web
    name: nm-connect-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
